version: "3"
services:
  redis:
    image: redis
    container_name: cache
    expose:
    - 6379
  app:
    build: .
    depends_on:
    - postgres
    - redis
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      REDIS_URL: redis://cache
      NODE_ENV: development
      PORT: 3000
    ports:
    - "3000:3000"
    command: npm run dev
    volumes:
    - .:/app/
    - /app/node_modules

  postgres:
    image: postgres:10.4
    container_name: postgres
    ports:
    - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./DDL/create-config-item-table.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 6